### ISSUE TITLE
Mars zoom bug, when zooming in once from specific level, tiles not displayed.

### ISSUE THREAD

**Issue by D4n2021** [dschwen/wikiminiatlas_servers#1]
When using [this](https://wma.wmflabs.org/iframe_dev.html?wma=-4.5895_137.4417_700_400_en_5_en&globe=Mars&lang=en&page=Curiosity_(rover)) link, then zooming out 4 times, then zooming in once, there is a grey bar in the center.

![grafik](https://user-images.githubusercontent.com/20766261/57162528-cf5af700-6dee-11e9-9520-1ad993868b93.png)

**Comment by D4n2021** [comment]
Reproducable in Firefox aswell as Chrome.

**Comment by dschwen** [comment]
Hm, sorry for the super late reply. But I cannot reproduce this anymore. I've recently gotten back to working on this project. This looks like a DNS lookup for one of the tile server aliases didn't work. All the tiles are there on the server and they load fine now.
